name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  id-token: write  # Required for JWT (Sigstore)

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      # Checkout code with witness-run-action wrapper
      - name: Checkout with Witness
        uses: testifysec/witness-run-action@main
        with:
          step: "checkout"
          action-ref: "actions/checkout@v4"
          enable-sigstore: true
          attestations: "environment github slsa"
      
      # Setup Go with witness-run-action wrapper (Composite action)
      - name: Setup Go with Witness
        uses: testifysec/witness-run-action@main
        with:
          step: "setup-go"
          action-ref: "actions/setup-go@v5"
          input-go-version: '1.22'
          input-cache: true
          enable-sigstore: true
          attestations: "environment github"
      
      # Run Go tests with witness-run-action wrapper (Command-line action)
      - name: Run Tests with Witness
        uses: testifysec/witness-run-action@main
        with:
          step: "run-tests"
          command: "go test -v ./..."
          enable-sigstore: true
          attestations: "environment github"
  
  build:
    name: Build with GoReleaser
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Checkout code with witness-run-action wrapper
      - name: Checkout with Witness
        uses: testifysec/witness-run-action@main
        with:
          step: "checkout-for-build"
          action-ref: "actions/checkout@v4"
          input-fetch-depth: 0
          enable-sigstore: true
          attestations: "environment github slsa"
      
      # Setup Go with witness-run-action wrapper
      - name: Setup Go with Witness
        uses: testifysec/witness-run-action@main
        with:
          step: "setup-go-for-build"
          action-ref: "actions/setup-go@v5"
          input-go-version: '1.22'
          enable-sigstore: true
          attestations: "environment github"
      
      # Run GoReleaser with witness-run-action wrapper (Docker action)
      - name: Run GoReleaser with Witness
        uses: testifysec/witness-run-action@main
        with:
          step: "goreleaser"
          action-ref: "goreleaser/goreleaser-action@v5"
          input-version: latest
          input-args: release --snapshot --clean
          enable-sigstore: true
          enable-archivista: true
          attestations: "environment github slsa"